sudo: required
services:
  - docker

before_install:
  - docker build -t jjxx/docker-react -f Dockerfile.dev .

script:
  - docker run jjxx/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-633621172169"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"    